services:
  app:
    image: todo:latest
    ports:
      - 8000:8000
    env_file:
      - path: .env
        required: false
    volumes:
      - ./data:/app/data
    
#   db:
#     image: postgres
#     restart: always
#     user: postgres
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=todo
#       - POSTGRES_PASSWORD=postgres
#     healthcheck:
#       test: [ "CMD", "pg_isready" ]
#       interval: 10s
#       timeout: 5s
#       retries: 5


networks:
  default:
    external: true
    name: npm
  host:
    external: true