services:
  # migration:
  #   image: ${DOCKER_IMAGE}
  #   command: alembic upgrade head
  #   env_file:
  #     - .env
  #   depends_on:
  #     db:
  #       condition: service_healthy

  app:
    image: ${DOCKER_IMAGE}
    ports:
      - 8000:8000
    # depends_on:
    #   - migration
    # volumes_from:
    #   - migrations
    env_file:
      - .env
    
#   db:
#     image: postgres
#     restart: always
#     user: postgres
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=todo
#       - POSTGRES_PASSWORD=postgres
#     healthcheck:
#       test: [ "CMD", "pg_isready" ]
#       interval: 10s
#       timeout: 5s
#       retries: 5

# volumes:
#   db-data:

networks:
  default:
    external: true
    name: npm
  host:
    external: true