services:
  app:
    image: todo:latest
    ports:
      - 8000:8000
    env_file:
      - path: .env
        required: false
    volumes:
      - ./data:/app/data

networks:
  default:
    external: true
    name: npm
  host:
    external: true