@base=http://localhost:8000/api
@todo_id=
@user_id=de9ef919-5157-43c5-8179-1cdf80cfe462
### Get todos
GET {{base}}/todos
### Create todo
POST {{base}}/todos
Content-Type: application/json

{
    "name": "Heloo",
    "done": false,
    "user_id": "{{user_id}}"
}
### Put changes
PATCH {{base}}/todos/{{todo_id}}
Content-Type: application/json

{
    "done": false,
    "name": "new name"
}
### Put changes 2
PATCH {{base}}/todos/
Content-Type: application/json

{
    "id": "{{todo_id}}",
    "done": true,
    "name": "some name"
}
### Users
GET {{base}}/users/
### Create user
POST {{base}}/users/
Content-Type: application/json

{
    "name": "Arwi"
}
