name: Update

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  run_pull:
    name: Run Pull
    runs-on: ubuntu-latest
    steps:
      - name: Connect and pull
        run: |
          echo "{{ secrets.SSH_PRIVATE_KEY }}" |
          ssh -i /dev/stdin {{ secrets.SSH_USER }}@{{ secrets.SSH_HOST }} "cd {{ secrets.WORK_DIR }} && git chekout main && git pull"

  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update
        run: |
          make update