name: Update

on:
  release:
    types: [published]


jobs:
  run_pull:
    name: Run Pull
    runs-on: ubuntu-latest
    steps:
      - name: Install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: Pull
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "\
            cd ${{ secrets.WORK_DIR }} &&\
            git checkout main && \
            git pull && \
            docker build -t ${{ secrets.DOCKER_IMAGE }} . && \
            docker compose up -e "DOCKER_IMAGE=${{ secrets.DOCKER_IMAGE }}" -d --build"
      - name: Cleanup
        run: |
          rm -rf ~/.ssh
